# https://starship.rs/guide
# https://starship.rs/config
# https://starship.rs/presets

# https://starship.rs/advanced-config/#style-strings
# styles:
#   bold, italic, underline, dimmed, inverted, bg:<color>, fg:<color>, <color>, none
# colors:
#   name: [bright-] black, red, green, blue, yellow, purple, cyan, white,
#   rgb:  #000000 (RGB hex code)
#   ansi: 0-255 (8-bit ANSI color code)

# https://github.com/mickimnet/myth-prompt-themes/blob/main/dark/slanted/starship/starship.toml

# 
# 
# 
# 
# ╱

# Colors
# #464347 desaturated purple (bg)
# #111111 almost black (fg)
# #EEEEEE almost white (fg)
# #ffA200 orange (time, jobs)
# #E0B25D pale orange (git_status)
# #6F6A70 desaturated purple (directory)
# #ff3322 red (directory: read-only, character: error)
# #96ab5f olive green (git_branch)
# #FBDE2D yellow (cmd_duration)
# #AFD700 green (character: success, vi_cmd)

# Prompt
format = """
$time\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hostname\
$custom\
$jobs\
$cmd_duration\
$character\
"""
# $cmd_duration\

# right_format = "$time" # only supported in zsh, fish, elvish

add_newline = false
command_timeout = 100
scan_timeout = 100

# Enabled modules (alternative to top-level `format`)
# status.disabled = false

# Disabled modules (alternative to top-level `format`)
# aws.disabled = true
# line_break.disabled = true

[time]
# format = "[ $time ]($style)"
# style = "fg:#cccccc bg:#333333"
# time_format = "%F %T" # https://docs.rs/chrono/latest/chrono/format/strftime/index.html
# disabled = false

#format = "[[ ](fg:#FFA200) $time[](bg:#464347 fg:#FFA200)]($style)"
#style = "bg:#FFA200 fg:#111111"
disabled = false
time_format = "%T" # https://docs.rs/chrono/latest/chrono/format/strftime/index.html
# time_range = "20:00:00-06:00:00"


# TODO
# [username]

[directory]
#format = "([[ ](bg:#464347 fg:#ff3322)$read_only[](bg:#464347 fg:#ff3322)]($read_only_style))[[ ](bg:#464347 fg:#6F6A70)$path[](bg:#464347 fg:#6F6A70)]($style)"
#style = "bg:#6F6A70 fg:#EEEEEE"
read_only_style = "bg:#ff3322 fg:#EEEEEE"
read_only = "" # lock icon?
truncate_to_repo  = true
truncation_length = 6
truncation_symbol = "…/"

[git_branch]
#format = "[[ ](bg:#464347 fg:#96ab5f)$symbol$branch[](bg:#464347 fg:#96ab5f)]($style)"
#style = "bg:#96ab5f fg:#111111"
symbol = " "
# symbol = " "
# symbol = " "
# symbol = " "

[git_status]
#format = "([[ ](bg:#464347 fg:#E0B25D)$stashed$staged$modified$renamed$untracked$deleted$conflicted$ahead_behind[](bg:#464347 fg:#E0B25D)]($style))"
#style     = "bg:#E0B25D fg:#000000"
ahead      = " ${count}" # nf-cod-arrow_small_up
behind     = " ${count}" # nf-cod-arrow_small_down
conflicted = " ${count}" # nf-fa-flag
diverged   = " 󰯎${ahead_count} ${behind_count}" # nf-md-swap_vertical_bold
deleted    = " ${count}" # nf-fa-remove
modified   = " ${count}" # nf-fa-pencil
renamed    = " 󰗧${count}" # nf-md-cursor_text
staged     = " ${count}" # nf-fa-check
stashed    = " ${count}" # nf-fa-inbox
untracked  = " ${count}" # nf-fa-question
up_to_date = ""
#
# Broken
#
# ahead      = "⇡ ${count}"
# behind     = "ﲔ ${count}"
# conflicted = "${count}"
# deleted    = " ${count}"
# diverged   = "李 ${ahead_count} ${behind_count}"
# modified   = " 凜${count}"
# renamed    = "﫦${count}"
# staged     = "  ${count}"
# stashed    = " ${count}"
# untracked  = "  ${count}"

# ignore_submodules = true

[jobs]
format = "[$symbol$number]($style)"
#style = "bold bg:#464347 fg:#FFA200"
symbol = "  " # nf-fa-gears
number_threshold = 1
symbol_threshold = 1

[cmd_duration]
format = "[  $duration]($style)" # nf-oct-stopwatch
#style = "bg:#464347 fg:#FBDE2D"
min_time = 5_000
show_milliseconds = true
#show_notifications = true
min_time_to_notify = 120_000

[character]
#format = "[[ ](bg:#464347)$symbol ]($style)"
#success_symbol = "[ ](bg:#464347 fg:#AFD700)[](fg:#464347)"
#error_symbol   = "[ ](bg:#464347 fg:#FF3322)[](fg:#464347)"
#vicmd_symbol   = "[ ](bg:#464347 fg:#AFD700)[](bg:#464347 fg:#111111)"

